import React, { useState } from 'react';
import { useSecurity } from '../../context/SecurityContext';
import {
  FileText,
  Download,
  Printer,
  Copy,
  Check,
  Shield,
  RefreshCw
} from 'lucide-react';

export const SecurityReportsView: React.FC = () => {
  const { currentProject } = useSecurity();

  const [isCopied, setIsCopied] = useState(false);
  const [reportDate, setReportDate] = useState(new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }));
  const [isRegenerating, setIsRegenerating] = useState(false);

  const criticalCount = currentProject.threats.filter(t => t.impact === 'Critical' || t.riskScore >= 9.0).length;
  const highCount = currentProject.threats.filter(t => t.impact === 'High' || (t.riskScore >= 7.0 && t.riskScore < 9.0)).length;
  const passedTests = currentProject.testCases.filter(t => t.status === 'Passed').length;
  const implementedMitigations = currentProject.mitigations.filter(m => m.status === 'Implemented').length;

  const handlePrintPdf = () => {
    window.print();
  };

  const handleExportJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(currentProject, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${currentProject.name}-Security-Audit-Report.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleCopyMarkdown = () => {
    const md = `# ThreatGuard AI Security Assessment Report: ${currentProject.name}
**Date:** ${reportDate}
**System Type:** ${currentProject.systemType} | **Version:** ${currentProject.version}
**Security Score:** ${currentProject.securityScore}/100

## Executive Summary
This report details the automated threat modeling, attack surface discovery, STRIDE analysis, and security validation results for ${currentProject.name}. The system consists of ${currentProject.components.length} embedded components, ${currentProject.attackSurfaces.length} exposed attack surfaces, and ${currentProject.threats.length} evaluated threat vectors.

### Key Risk Metrics:
- **Critical Threats:** ${criticalCount}
- **High Risk Threats:** ${highCount}
- **Automated Security Tests:** ${passedTests} passed of ${currentProject.testCases.length}
- **Mitigation Implementation:** ${implementedMitigations} of ${currentProject.mitigations.length} resolved

## Top Critical Threats
${currentProject.threats.map(t => `- **[${t.id}] ${t.title}** (${t.category} / Risk: ${t.riskScore}) on ${t.component}\n  *Mitigation:* ${t.recommendedMitigation}`).join('\n')}

---
Generated by ThreatGuard AI Embedded Cybersecurity Engine.
`;
    navigator.clipboard.writeText(md);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    await new Promise(r => setTimeout(r, 600));
    setReportDate(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
    setIsRegenerating(false);
  };

  return (
    <div className="p-3.5 sm:p-6 lg:p-8 space-y-5 sm:space-y-6 max-w-7xl mx-auto">
      {/* Action Bar (Hidden in Print) */}
      <div className="no-print flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-4 sm:pb-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-blue-400 uppercase tracking-wider font-mono">
              Audit Deliverable
            </span>
            <span className="text-slate-600">·</span>
            <span className="text-xs text-slate-400 font-mono">Executive &amp; Technical Report</span>
          </div>
          <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white mt-1">
            Security Assessment Report
          </h1>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            ISO/SAE 21434 &amp; UNECE WP.29 R155 compliant comprehensive security audit document ready for certification.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleRegenerate}
            disabled={isRegenerating}
            className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            <RefreshCw className={`h-3 w-3 ${isRegenerating ? 'animate-spin' : ''}`} />
            <span>Regenerate</span>
          </button>
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            {isCopied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
            <span>{isCopied ? 'Copied' : 'Markdown'}</span>
          </button>
          <button
            onClick={handleExportJson}
            className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            <Download className="h-3 w-3" />
            <span>JSON</span>
          </button>
          <button
            onClick={handlePrintPdf}
            className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-blue-500 transition-colors shadow-sm"
          >
            <Printer className="h-3 w-3" />
            <span>PDF / Print</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document Sheet */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/90 p-4 sm:p-8 lg:p-10 shadow-xl space-y-6 sm:space-y-8 max-w-5xl mx-auto text-slate-200">
        {/* Document Header */}
        <div className="border-b border-slate-800 pb-5 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <div className="h-7 w-7 rounded-lg bg-blue-600 text-white font-bold flex items-center justify-center">
                <Shield className="h-4 w-4" />
              </div>
              <span className="text-lg font-bold tracking-tight text-white">ThreatGuard AI</span>
              <span className="text-xs font-mono bg-slate-800 text-slate-300 px-2 py-0.5 rounded border border-slate-700">
                AUDIT REPORT
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white mt-2">{currentProject.name}</h2>
            <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400 font-mono mt-1">
              <span>System: <strong>{currentProject.systemType}</strong></span>
              <span>·</span>
              <span>Version: <strong>{currentProject.version}</strong></span>
              <span>·</span>
              <span>Date: <strong>{reportDate}</strong></span>
            </div>
          </div>

          <div className="bg-slate-950 border border-slate-800 p-3.5 rounded-xl text-left sm:text-right shrink-0">
            <div className="text-[10px] font-mono uppercase text-slate-400">Security Score</div>
            <div className="text-2xl sm:text-3xl font-extrabold text-blue-400 font-mono">
              {currentProject.securityScore}/100
            </div>
            <div className="text-[10px] text-emerald-400 font-mono mt-0.5">ISO 21434 Target &gt;= 85</div>
          </div>
        </div>

        {/* 1. Executive Summary */}
        <section className="space-y-2.5">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono text-blue-400">
            01. Executive Summary
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed">
            ThreatGuard AI has performed a rigorous automated threat modeling, attack surface discovery, and security verification analysis on <strong>{currentProject.name}</strong>. The assessment covers physical transceivers, wireless telemetry, operating systems, intra-vehicle buses (CAN-FD, LIN, BroadR-Reach Ethernet), and diagnostic services (ISO 14229 UDS).
          </p>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 pt-2 text-center text-xs font-mono">
            <div className="bg-slate-950 p-2.5 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Components</span>
              <span className="text-lg font-bold text-white">{currentProject.components.length}</span>
            </div>
            <div className="bg-slate-950 p-2.5 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Surfaces</span>
              <span className="text-lg font-bold text-amber-400">{currentProject.attackSurfaces.length}</span>
            </div>
            <div className="bg-slate-950 p-2.5 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Critical</span>
              <span className="text-lg font-bold text-red-400">{criticalCount}</span>
            </div>
            <div className="bg-slate-950 p-2.5 rounded-lg border border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Mitigations</span>
              <span className="text-lg font-bold text-emerald-400">{implementedMitigations}/{currentProject.mitigations.length}</span>
            </div>
          </div>
        </section>

        {/* 2. Architecture & Trust Boundary Summary */}
        <section className="space-y-2.5">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono text-blue-400">
            02. Architecture &amp; Trust Boundaries
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed">
            The system architecture spans four distinct trust boundaries: <strong>Untrusted External</strong>, <strong>Gateway Firewall Domain</strong>, <strong>Isolated Safety Domain (ASIL-D)</strong>, and <strong>Cloud Edge</strong>.
          </p>
          <div className="space-y-1.5 text-xs font-mono overflow-x-auto">
            {currentProject.components.map((c) => (
              <div key={c.id} className="flex items-center justify-between p-2 rounded bg-slate-950 border border-slate-800 min-w-[500px]">
                <span className="font-semibold text-white">{c.name}</span>
                <span className="text-slate-400">{c.trustBoundary}</span>
                <span className="text-blue-400 truncate max-w-[200px]">{c.interfaces.join(', ')}</span>
                <span className={c.riskLevel === 'Critical' ? 'text-red-400 font-bold' : 'text-slate-300'}>
                  {c.riskLevel}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* 3. Prioritized STRIDE Threats */}
        <section className="space-y-2.5 report-page-break">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono text-blue-400">
            03. Prioritized STRIDE Threat Model
          </h3>
          <div className="space-y-2">
            {currentProject.threats.map((t) => (
              <div key={t.id} className="p-3 rounded-lg bg-slate-950 border border-slate-800 space-y-1 text-xs">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-blue-400">{t.id}</span>
                    <span className="font-semibold text-white">{t.title}</span>
                  </div>
                  <span className="font-mono font-bold text-red-400">Risk {t.riskScore}/10</span>
                </div>
                <p className="text-slate-300 leading-relaxed">{t.description}</p>
                <div className="flex flex-wrap items-center justify-between text-[11px] font-mono text-slate-400 pt-1 border-t border-slate-850">
                  <span>Category: <strong>{t.category}</strong> · Target: <strong>{t.component}</strong></span>
                  <span className="text-emerald-400">Fix: {t.recommendedMitigation}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Footer Signature */}
        <div className="pt-4 border-t border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs text-slate-500 font-mono">
          <div>ThreatGuard AI Embedded Cybersecurity Suite</div>
          <div>Audited &amp; Approved for Release</div>
        </div>
      </div>
    </div>
  );
};
